// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countMenuItemModifierGroups = `-- name: CountMenuItemModifierGroups :one
select count(*) from menu_item_modifier_groups
`

func (q *Queries) CountMenuItemModifierGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMenuItemModifierGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCashierMenuRows = `-- name: ListCashierMenuRows :many
select
	c.id as category_id,
	c.name as category_name,
	c.slug as category_slug,
	i.id as item_id,
	i.name as item_name,
	i.slug as item_slug,
	i.price_rp,
	i.image_path,
	i.popularity_rank,
	i.best_seller,
	i.promo,
	i.iced,
	i.low_sugar,
	i.new_arrival,
	g.id as group_id,
	g.name as group_name,
	g.slug as group_slug,
	g.required,
	g.selection_type,
	o.id as option_id,
	o.name as option_name,
	o.slug as option_slug,
	o.price_delta_rp
from menu_categories c
join menu_items i on i.category_id = c.id and i.active = true
left join menu_item_modifier_groups mig on mig.menu_item_id = i.id
left join modifier_groups g on g.id = mig.modifier_group_id
left join modifier_options o on o.modifier_group_id = g.id
order by c.sort_order, c.id, i.sort_order, i.id, mig.sort_order, g.sort_order, g.id, o.sort_order, o.id
`

type ListCashierMenuRowsRow struct {
	CategoryID     int64
	CategoryName   string
	CategorySlug   string
	ItemID         int64
	ItemName       string
	ItemSlug       string
	PriceRp        int32
	ImagePath      sql.NullString
	PopularityRank sql.NullInt32
	BestSeller     bool
	Promo          bool
	Iced           bool
	LowSugar       bool
	NewArrival     bool
	GroupID        sql.NullInt64
	GroupName      sql.NullString
	GroupSlug      sql.NullString
	Required       sql.NullBool
	SelectionType  sql.NullString
	OptionID       sql.NullInt64
	OptionName     sql.NullString
	OptionSlug     sql.NullString
	PriceDeltaRp   sql.NullInt32
}

func (q *Queries) ListCashierMenuRows(ctx context.Context) ([]ListCashierMenuRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCashierMenuRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCashierMenuRowsRow
	for rows.Next() {
		var i ListCashierMenuRowsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.ItemID,
			&i.ItemName,
			&i.ItemSlug,
			&i.PriceRp,
			&i.ImagePath,
			&i.PopularityRank,
			&i.BestSeller,
			&i.Promo,
			&i.Iced,
			&i.LowSugar,
			&i.NewArrival,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlug,
			&i.Required,
			&i.SelectionType,
			&i.OptionID,
			&i.OptionName,
			&i.OptionSlug,
			&i.PriceDeltaRp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuCategories = `-- name: ListMenuCategories :many
select id, name, slug, sort_order
from menu_categories
order by sort_order, id
`

type ListMenuCategoriesRow struct {
	ID        int64
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) ListMenuCategories(ctx context.Context) ([]ListMenuCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMenuCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuCategoriesRow
	for rows.Next() {
		var i ListMenuCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
select
	id,
	category_id,
	name,
	slug,
	price_rp,
	active,
	sort_order,
	image_path,
	popularity_rank,
	best_seller,
	promo,
	iced,
	low_sugar,
	new_arrival
from menu_items
order by sort_order, id
`

type ListMenuItemsRow struct {
	ID             int64
	CategoryID     int64
	Name           string
	Slug           string
	PriceRp        int32
	Active         bool
	SortOrder      int32
	ImagePath      sql.NullString
	PopularityRank sql.NullInt32
	BestSeller     bool
	Promo          bool
	Iced           bool
	LowSugar       bool
	NewArrival     bool
}

func (q *Queries) ListMenuItems(ctx context.Context) ([]ListMenuItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsRow
	for rows.Next() {
		var i ListMenuItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.PriceRp,
			&i.Active,
			&i.SortOrder,
			&i.ImagePath,
			&i.PopularityRank,
			&i.BestSeller,
			&i.Promo,
			&i.Iced,
			&i.LowSugar,
			&i.NewArrival,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierGroups = `-- name: ListModifierGroups :many
select id, name, slug, required, selection_type, sort_order
from modifier_groups
order by sort_order, id
`

type ListModifierGroupsRow struct {
	ID            int64
	Name          string
	Slug          string
	Required      bool
	SelectionType string
	SortOrder     int32
}

func (q *Queries) ListModifierGroups(ctx context.Context) ([]ListModifierGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModifierGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModifierGroupsRow
	for rows.Next() {
		var i ListModifierGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Required,
			&i.SelectionType,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierOptions = `-- name: ListModifierOptions :many
select id, modifier_group_id, name, slug, price_delta_rp, sort_order
from modifier_options
order by sort_order, id
`

type ListModifierOptionsRow struct {
	ID              int64
	ModifierGroupID int64
	Name            string
	Slug            string
	PriceDeltaRp    int32
	SortOrder       int32
}

func (q *Queries) ListModifierOptions(ctx context.Context) ([]ListModifierOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModifierOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModifierOptionsRow
	for rows.Next() {
		var i ListModifierOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModifierGroupID,
			&i.Name,
			&i.Slug,
			&i.PriceDeltaRp,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMenuCategory = `-- name: UpsertMenuCategory :one
insert into menu_categories (name, slug, sort_order, updated_at)
values ($1, $2, $3, now())
on conflict (slug) do update set
	name = excluded.name,
	sort_order = excluded.sort_order,
	updated_at = now()
returning id
`

type UpsertMenuCategoryParams struct {
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) UpsertMenuCategory(ctx context.Context, arg UpsertMenuCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMenuCategory, arg.Name, arg.Slug, arg.SortOrder)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMenuItem = `-- name: UpsertMenuItem :one
insert into menu_items (
	category_id,
	name,
	slug,
	price_rp,
	active,
	sort_order,
	image_path,
	popularity_rank,
	best_seller,
	promo,
	iced,
	low_sugar,
	new_arrival,
	updated_at
)
values ($1, $2, $3, $4, $5, $6, $12, $13, $7, $8, $9, $10, $11, now())
on conflict (category_id, slug) do update set
	name = excluded.name,
	price_rp = excluded.price_rp,
	active = excluded.active,
	sort_order = excluded.sort_order,
	image_path = excluded.image_path,
	popularity_rank = excluded.popularity_rank,
	best_seller = excluded.best_seller,
	promo = excluded.promo,
	iced = excluded.iced,
	low_sugar = excluded.low_sugar,
	new_arrival = excluded.new_arrival,
	updated_at = now()
returning id
`

type UpsertMenuItemParams struct {
	CategoryID     int64
	Name           string
	Slug           string
	PriceRp        int32
	Active         bool
	SortOrder      int32
	BestSeller     bool
	Promo          bool
	Iced           bool
	LowSugar       bool
	NewArrival     bool
	ImagePath      sql.NullString
	PopularityRank sql.NullInt32
}

func (q *Queries) UpsertMenuItem(ctx context.Context, arg UpsertMenuItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.PriceRp,
		arg.Active,
		arg.SortOrder,
		arg.BestSeller,
		arg.Promo,
		arg.Iced,
		arg.LowSugar,
		arg.NewArrival,
		arg.ImagePath,
		arg.PopularityRank,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMenuItemModifierGroup = `-- name: UpsertMenuItemModifierGroup :exec
insert into menu_item_modifier_groups (menu_item_id, modifier_group_id, sort_order)
values ($1, $2, $3)
on conflict (menu_item_id, modifier_group_id) do update set
	sort_order = excluded.sort_order
`

type UpsertMenuItemModifierGroupParams struct {
	MenuItemID      int64
	ModifierGroupID int64
	SortOrder       int32
}

func (q *Queries) UpsertMenuItemModifierGroup(ctx context.Context, arg UpsertMenuItemModifierGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertMenuItemModifierGroup, arg.MenuItemID, arg.ModifierGroupID, arg.SortOrder)
	return err
}

const upsertModifierGroup = `-- name: UpsertModifierGroup :one
insert into modifier_groups (name, slug, required, selection_type, sort_order, updated_at)
values ($1, $2, $3, $4, $5, now())
on conflict (slug) do update set
	name = excluded.name,
	required = excluded.required,
	selection_type = excluded.selection_type,
	sort_order = excluded.sort_order,
	updated_at = now()
returning id
`

type UpsertModifierGroupParams struct {
	Name          string
	Slug          string
	Required      bool
	SelectionType string
	SortOrder     int32
}

func (q *Queries) UpsertModifierGroup(ctx context.Context, arg UpsertModifierGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertModifierGroup,
		arg.Name,
		arg.Slug,
		arg.Required,
		arg.SelectionType,
		arg.SortOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertModifierOption = `-- name: UpsertModifierOption :one
insert into modifier_options (modifier_group_id, name, slug, price_delta_rp, sort_order, updated_at)
values ($1, $2, $3, $4, $5, now())
on conflict (modifier_group_id, slug) do update set
	name = excluded.name,
	price_delta_rp = excluded.price_delta_rp,
	sort_order = excluded.sort_order,
	updated_at = now()
returning id
`

type UpsertModifierOptionParams struct {
	ModifierGroupID int64
	Name            string
	Slug            string
	PriceDeltaRp    int32
	SortOrder       int32
}

func (q *Queries) UpsertModifierOption(ctx context.Context, arg UpsertModifierOptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertModifierOption,
		arg.ModifierGroupID,
		arg.Name,
		arg.Slug,
		arg.PriceDeltaRp,
		arg.SortOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
