// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type MenuCategory struct {
	ID        int64
	Name      string
	Slug      string
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MenuItem struct {
	ID         int64
	CategoryID int64
	Name       string
	Slug       string
	PriceRp    int32
	Active     bool
	SortOrder  int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type MenuItemModifierGroup struct {
	MenuItemID      int64
	ModifierGroupID int64
	SortOrder       int32
}

type ModifierGroup struct {
	ID            int64
	Name          string
	Slug          string
	Required      bool
	SelectionType string
	SortOrder     int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ModifierOption struct {
	ID              int64
	ModifierGroupID int64
	Name            string
	Slug            string
	PriceDeltaRp    int32
	SortOrder       int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
