// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const allocateDailyQueueNumber = `-- name: AllocateDailyQueueNumber :one
insert into daily_queue_counters (business_date, last_queue_number, updated_at)
values ($1, 1, now())
on conflict (business_date) do update set
	last_queue_number = daily_queue_counters.last_queue_number + 1,
	updated_at = now()
returning last_queue_number
`

func (q *Queries) AllocateDailyQueueNumber(ctx context.Context, businessDate time.Time) (int32, error) {
	row := q.db.QueryRowContext(ctx, allocateDailyQueueNumber, businessDate)
	var last_queue_number int32
	err := row.Scan(&last_queue_number)
	return last_queue_number, err
}

const cancelOrder = `-- name: CancelOrder :execrows
update orders
set status = 'cancelled',
	cancelled_at = $2,
	updated_at = now()
where id = $1
	and business_date = $3
	and status = 'paid'
`

type CancelOrderParams struct {
	ID           int64
	CancelledAt  sql.NullTime
	BusinessDate time.Time
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelOrder, arg.ID, arg.CancelledAt, arg.BusinessDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOrder = `-- name: CreateOrder :one
insert into orders (
	business_date,
	queue_number,
	status,
	payment_method,
	paid_at,
	cancelled_at,
	note,
	total_rp,
	client_request_id,
	request_hash,
	updated_at
)
values ($1, $2, 'paid', $3, $4, null, $5, $6, $7, $8, now())
returning id
`

type CreateOrderParams struct {
	BusinessDate    time.Time
	QueueNumber     int32
	PaymentMethod   string
	PaidAt          time.Time
	Note            sql.NullString
	TotalRp         int64
	ClientRequestID uuid.UUID
	RequestHash     []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.BusinessDate,
		arg.QueueNumber,
		arg.PaymentMethod,
		arg.PaidAt,
		arg.Note,
		arg.TotalRp,
		arg.ClientRequestID,
		arg.RequestHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderLine = `-- name: CreateOrderLine :one
insert into order_lines (
	order_id,
	menu_item_id,
	menu_item_slug,
	menu_item_name,
	unit_price_rp,
	quantity,
	line_total_rp,
	display_order
)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id
`

type CreateOrderLineParams struct {
	OrderID      int64
	MenuItemID   int64
	MenuItemSlug string
	MenuItemName string
	UnitPriceRp  int64
	Quantity     int32
	LineTotalRp  int64
	DisplayOrder int32
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrderLine,
		arg.OrderID,
		arg.MenuItemID,
		arg.MenuItemSlug,
		arg.MenuItemName,
		arg.UnitPriceRp,
		arg.Quantity,
		arg.LineTotalRp,
		arg.DisplayOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderLineModifier = `-- name: CreateOrderLineModifier :exec
insert into order_line_modifiers (
	order_line_id,
	modifier_group_id,
	modifier_option_id,
	group_slug,
	group_name,
	option_slug,
	option_name,
	price_delta_rp,
	display_order
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOrderLineModifierParams struct {
	OrderLineID      int64
	ModifierGroupID  int64
	ModifierOptionID int64
	GroupSlug        string
	GroupName        string
	OptionSlug       string
	OptionName       string
	PriceDeltaRp     int64
	DisplayOrder     int32
}

func (q *Queries) CreateOrderLineModifier(ctx context.Context, arg CreateOrderLineModifierParams) error {
	_, err := q.db.ExecContext(ctx, createOrderLineModifier,
		arg.OrderLineID,
		arg.ModifierGroupID,
		arg.ModifierOptionID,
		arg.GroupSlug,
		arg.GroupName,
		arg.OptionSlug,
		arg.OptionName,
		arg.PriceDeltaRp,
		arg.DisplayOrder,
	)
	return err
}

const getOrderIdempotency = `-- name: GetOrderIdempotency :one
select id, request_hash
from orders
where client_request_id = $1
`

type GetOrderIdempotencyRow struct {
	ID          int64
	RequestHash []byte
}

func (q *Queries) GetOrderIdempotency(ctx context.Context, clientRequestID uuid.UUID) (GetOrderIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderIdempotency, clientRequestID)
	var i GetOrderIdempotencyRow
	err := row.Scan(&i.ID, &i.RequestHash)
	return i, err
}

const getPaidOrder = `-- name: GetPaidOrder :many
select
	o.id as order_id,
	o.business_date,
	o.queue_number,
	o.status,
	o.payment_method,
	o.paid_at,
	o.cancelled_at,
	o.note,
	o.total_rp,
	ol.id as order_line_id,
	ol.menu_item_slug,
	ol.menu_item_name,
	ol.unit_price_rp,
	ol.quantity,
	ol.line_total_rp,
	ol.display_order as line_display_order,
	olm.group_slug,
	olm.group_name,
	olm.option_slug,
	olm.option_name,
	olm.price_delta_rp,
	olm.display_order as modifier_display_order
from orders o
join order_lines ol on ol.order_id = o.id
left join order_line_modifiers olm on olm.order_line_id = ol.id
where o.id = $1
order by ol.display_order, ol.id, olm.display_order, olm.id
`

type GetPaidOrderRow struct {
	OrderID              int64
	BusinessDate         time.Time
	QueueNumber          int32
	Status               string
	PaymentMethod        string
	PaidAt               time.Time
	CancelledAt          sql.NullTime
	Note                 sql.NullString
	TotalRp              int64
	OrderLineID          int64
	MenuItemSlug         string
	MenuItemName         string
	UnitPriceRp          int64
	Quantity             int32
	LineTotalRp          int64
	LineDisplayOrder     int32
	GroupSlug            sql.NullString
	GroupName            sql.NullString
	OptionSlug           sql.NullString
	OptionName           sql.NullString
	PriceDeltaRp         sql.NullInt64
	ModifierDisplayOrder sql.NullInt32
}

func (q *Queries) GetPaidOrder(ctx context.Context, id int64) ([]GetPaidOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaidOrder, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaidOrderRow
	for rows.Next() {
		var i GetPaidOrderRow
		if err := rows.Scan(
			&i.OrderID,
			&i.BusinessDate,
			&i.QueueNumber,
			&i.Status,
			&i.PaymentMethod,
			&i.PaidAt,
			&i.CancelledAt,
			&i.Note,
			&i.TotalRp,
			&i.OrderLineID,
			&i.MenuItemSlug,
			&i.MenuItemName,
			&i.UnitPriceRp,
			&i.Quantity,
			&i.LineTotalRp,
			&i.LineDisplayOrder,
			&i.GroupSlug,
			&i.GroupName,
			&i.OptionSlug,
			&i.OptionName,
			&i.PriceDeltaRp,
			&i.ModifierDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
